import { useEffect } from 'react';
import type { MouseEvent as ReactMouseEvent } from 'react';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { invoke } from '@tauri-apps/api/core';
import { ChatView } from '../chat/ChatView';
import { NavRail } from '../layout/NavRail';
import { ProjectList } from '../projects/ProjectList';
import { SettingsPage } from '../settings/SettingsPage';
import { CustomizePage } from '../settings/CustomizePage';
import { useAppStore } from '../stores/appStore';
import { t } from '../lib/i18n';
type ResizeDirection = 'East' | 'North' | 'NorthEast' | 'NorthWest' | 'South' | 'SouthEast' | 'SouthWest' | 'West';
export function App() { const { view, setView, newSession, addProject, cancel, settings } = useAppStore(); const appWindow = getCurrentWindow(); useEffect(() => { void invoke('ensure_wedex_root').catch(console.error); }, []); useEffect(() => { document.documentElement.dataset.theme = settings.theme; document.documentElement.lang = settings.language ?? 'zh-CN'; document.documentElement.style.fontSize = `${settings.fontSize}px`; const handler = (e: KeyboardEvent) => { if (!e.metaKey && !e.ctrlKey) return; if (e.key.toLowerCase() === 'n') { e.preventDefault(); void newSession(); } if (e.key.toLowerCase() === 'o') { e.preventDefault(); const path = window.prompt(t(settings.language, 'promptProjectPath')); if (path) addProject(path); } if (e.key === ',') { e.preventDefault(); setView('settings'); } if (e.key === 'Escape') cancel(); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [settings.theme, settings.language, settings.fontSize, addProject, cancel, newSession, setView]); const startWindowDrag = (event: ReactMouseEvent<HTMLDivElement>) => { if (event.button !== 0) return; const target = event.target as HTMLElement; if (target.closest('button,input,textarea,select,a,[role="button"],.project-row,.bubble,.composer,.message')) return; void appWindow.startDragging().catch(console.error); }; const startResize = (direction: ResizeDirection) => (event: ReactMouseEvent<HTMLDivElement>) => { event.stopPropagation(); void appWindow.startResizeDragging(direction).catch(console.error); }; return <div className="app-shell" onMouseDown={startWindowDrag}><div className="window-drag-strip" data-tauri-drag-region/><div className="resize-handle resize-n" onMouseDown={startResize('North')}/><div className="resize-handle resize-e" onMouseDown={startResize('East')}/><div className="resize-handle resize-s" onMouseDown={startResize('South')}/><div className="resize-handle resize-w" onMouseDown={startResize('West')}/><div className="resize-handle resize-ne" onMouseDown={startResize('NorthEast')}/><div className="resize-handle resize-nw" onMouseDown={startResize('NorthWest')}/><div className="resize-handle resize-se" onMouseDown={startResize('SouthEast')}/><div className="resize-handle resize-sw" onMouseDown={startResize('SouthWest')}/><NavRail /><ProjectList />{view === 'settings' ? <SettingsPage /> : view === 'customize' ? <CustomizePage /> : <ChatView />}</div>; }
