import { create } from 'zustand';
import { invoke } from '@tauri-apps/api/core';
import type { CodexEvent, CodexStatus, Message, Project, Session, Settings } from '../types';
import { id } from '../lib/id';
import { defaults, load, save } from '../database/local';
import { runMockTask } from '../codex/mockAdapter';
import { cliAdapter } from '../services/codexAdapter';
import { t } from '../lib/i18n';
const initial = load();
type View = 'chat' | 'projects' | 'history' | 'settings' | 'customize';
interface AppState { projects: Project[]; sessions: Session[]; messages: Message[]; settings: Settings; selectedProjectId?: string; selectedSessionId?: string; view: View; running: boolean; status: CodexStatus; activity: string; addProject(path: string): void; select(projectId: string, sessionId?: string): void; newSession(projectId?: string): Promise<void>; renameProject(projectId: string, name: string): void; renameSession(sessionId: string, title: string): void; removeProject(projectId: string): void; updateSettings(settings: Partial<Settings>): void; setView(view: View): void; send(prompt: string): Promise<void>; cancel(): void; }
const persist = (state: Pick<AppState, 'projects' | 'sessions' | 'messages' | 'settings'>) => save(state);
export const useAppStore = create<AppState>((set, get) => ({
  projects: initial.projects, sessions: initial.sessions, messages: initial.messages, settings: initial.settings ?? defaults, selectedProjectId: initial.projects[0]?.id, selectedSessionId: initial.projects[0]?.currentSessionId, view: 'chat', running: false, status: 'idle', activity: '',
  addProject(path) { const current = get(); if (current.projects.some((p) => p.path === path)) return; const name = path.split(/[\\/]/).filter(Boolean).pop() || '未命名项目'; const projectId = id('project'); const sessionId = id('session'); const project: Project = { id: projectId, name, path, branch: 'main', updatedAt: Date.now(), pinned: false, currentSessionId: sessionId }; const session: Session = { id: sessionId, projectId, title: '新会话', updatedAt: Date.now(), status: 'idle' }; set({ projects: [project, ...current.projects], sessions: [session, ...current.sessions], selectedProjectId: projectId, selectedSessionId: sessionId, view: 'chat' }); void invoke('create_session_directory', { projectPath: path, sessionId }).catch(console.error); persist(get()); },
  select(projectId, sessionId) { const p = get().projects.find((project) => project.id === projectId); const selectedSessionId = sessionId ?? p?.currentSessionId; set((state) => ({ projects: sessionId ? state.projects.map((project) => project.id === projectId ? { ...project, currentSessionId: sessionId } : project) : state.projects, selectedProjectId: projectId, selectedSessionId, view: 'chat' })); persist(get()); },
  async newSession(projectId) { const pid = projectId ?? get().selectedProjectId; if (!pid) return; const project = get().projects.find((item) => item.id === pid); if (!project) return; const session: Session = { id: id('session'), projectId: pid, title: '新对话', updatedAt: Date.now(), status: 'idle' }; await invoke('create_session_directory', { projectPath: project.path, sessionId: session.id }); set((s) => ({ sessions: [session, ...s.sessions], projects: s.projects.map((p) => p.id === pid ? { ...p, currentSessionId: session.id, updatedAt: Date.now() } : p), selectedProjectId: pid, selectedSessionId: session.id, view: 'chat' })); persist(get()); },
  renameProject(projectId, name) { const nextName = name.trim().slice(0, 80); if (!nextName) return; set((state) => ({ projects: state.projects.map((project) => project.id === projectId ? { ...project, name: nextName, updatedAt: Date.now() } : project) })); persist(get()); },
  renameSession(sessionId, title) { const nextTitle = title.trim().slice(0, 80); if (!nextTitle) return; set((state) => ({ sessions: state.sessions.map((session) => session.id === sessionId ? { ...session, title: nextTitle, updatedAt: Date.now() } : session) })); persist(get()); },
  removeProject(projectId) { set((s) => ({ projects: s.projects.filter((p) => p.id !== projectId), sessions: s.sessions.filter((x) => x.projectId !== projectId), messages: s.messages.filter((x) => x.projectId !== projectId), selectedProjectId: undefined, selectedSessionId: undefined })); persist(get()); },
  updateSettings(settings) { set((s) => ({ settings: { ...s.settings, ...settings } })); persist(get()); }, setView(view) { set({ view }); },
  async send(prompt) { const { selectedProjectId: projectId, selectedSessionId: sessionId, running, settings, projects } = get(); if (!projectId || !sessionId || running || !prompt.trim()) return; const append = (event: CodexEvent) => { const message: Message = { id: id('msg'), projectId, sessionId, type: event.type, content: event.content, status: event.status, createdAt: Date.now(), metadata: event.metadata ?? {} }; const hidden = event.type === 'thinking' || event.type === 'status' || event.type === 'raw_log' || event.type === 'command' || event.type === 'command_result' || event.type === 'file_read' || event.type === 'file_edit' || event.type === 'diff' || event.type === 'approval' || event.type === 'completed' || event.type === 'system'; const retry = event.content.match(/(?:Reconnecting(?:\.{1,3}|…)?\s*|重连\s*)(\d+)\s*\/\s*\d+/i)?.[1]; const activity = event.type === 'completed' || event.type === 'error' ? '' : retry ? t(settings.language, 'typingRetry', { count: retry }) : t(settings.language, 'typing'); set((s) => ({ messages: hidden ? s.messages : [...s.messages, message], activity, status: event.status, running: event.type === 'completed' || event.type === 'error' ? false : s.running, sessions: s.sessions.map((x) => x.id === sessionId ? { ...x, status: event.status, updatedAt: Date.now(), title: x.title === '新会话' || x.title === '新对话' ? prompt.slice(0, 32) : x.title } : x) })); };
    append({ type: 'user', content: prompt, status: 'starting' }); set({ running: true, status: 'starting' }); try { if (settings.adapter === 'cli') await cliAdapter.run(projects.find((project) => project.id === projectId)?.path ?? '', prompt, settings.cliPath, settings.language, append); else await runMockTask(prompt, settings.language, append, () => !get().running); if (settings.adapter === 'mock' && get().running) set({ running: false, status: 'completed' }); } catch (error) { append({ type: 'error', content: error instanceof Error ? error.message : String(error), status: 'error' }); } finally { persist(get()); } },
  cancel() { set({ running: false, status: 'cancelled' }); const { selectedProjectId: projectId, selectedSessionId: sessionId } = get(); if (projectId && sessionId) set((s) => ({ messages: [...s.messages, { id: id('msg'), projectId, sessionId, type: 'system', content: '任务已由用户停止。', status: 'cancelled', createdAt: Date.now(), metadata: {} }] })); persist(get()); }
}));
